services:
  db:
    image: postgres:15-alpine
    container_name: transcendence_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ..
      dockerfile: srcs/frontend/Dockerfile
    container_name: transcendence_frontend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: ${FRONTEND_PORT}
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: transcendence_proxy
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - nginx_certs:${CRED_PATH}

volumes:
  postgres_data:
  nginx_certs: